/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.CardLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        purchasing = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        miscellany = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        purchasingPanel = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        logOut1 = new javax.swing.JButton();
        prchOrd = new javax.swing.JButton();
        prchLst = new javax.swing.JButton();
        mainPurchasingPanel = new javax.swing.JPanel();
        purchasePanelOne = new javax.swing.JPanel();
        selectSupplier = new javax.swing.JButton();
        receivedStock = new javax.swing.JButton();
        returnsStock = new javax.swing.JButton();
        supplierPanel = new javax.swing.JPanel();
        supplierPanelOne = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        supplierPanelTwo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        supplierPanelThree = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        purchasePanelTwo = new javax.swing.JPanel();
        purchasedOrder = new javax.swing.JButton();
        unreceivedOrder = new javax.swing.JButton();
        unpaidOrder = new javax.swing.JButton();
        purchaseListPanel = new javax.swing.JPanel();
        subPurchaseListPanelOne = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subPurchaseListPanelTwo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        subPurchaseListPanelThree = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inventoryPanel = new javax.swing.JPanel();
        close2 = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        logOut2 = new javax.swing.JButton();
        stocks = new javax.swing.JButton();
        products = new javax.swing.JButton();
        archery = new javax.swing.JButton();
        mainInventoryPanel = new javax.swing.JPanel();
        inventoryPanelOne = new javax.swing.JPanel();
        currentStock = new javax.swing.JButton();
        reOrderPoint = new javax.swing.JButton();
        adjustStock = new javax.swing.JButton();
        ledger = new javax.swing.JButton();
        stocksPanel = new javax.swing.JPanel();
        stocksPanelOne = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        stocksPanelTwo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        stocksPanelThree = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        stocksPanelFour = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        inventoryPanelTwo = new javax.swing.JPanel();
        newProduct = new javax.swing.JButton();
        productCategory = new javax.swing.JButton();
        productList = new javax.swing.JButton();
        productsPanel = new javax.swing.JPanel();
        productsPanelOne = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        productsPanelTwo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        productsPanelThree = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        inventoryPanelThree = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        miscellanyPanel = new javax.swing.JPanel();
        close3 = new javax.swing.JLabel();
        back3 = new javax.swing.JLabel();
        logOut3 = new javax.swing.JButton();
        suppliers = new javax.swing.JButton();
        employees = new javax.swing.JButton();
        orders = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        mainMiscellanyPanel = new javax.swing.JPanel();
        miscellanyPanelOne = new javax.swing.JPanel();
        newSupplier = new javax.swing.JButton();
        suppierList = new javax.swing.JButton();
        suppliersPanel = new javax.swing.JPanel();
        suppliersPanelOne = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        suppliersPanelTwo = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        miscellanyPanelTwo = new javax.swing.JPanel();
        newEmployee = new javax.swing.JButton();
        employeeList = new javax.swing.JButton();
        employeesPanel = new javax.swing.JPanel();
        employeesPanelOne = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        employeesPanelTwo = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        miscellanyPanelThree = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        miscellanyPanelFour = new javax.swing.JPanel();
        sales = new javax.swing.JButton();
        prchs = new javax.swing.JButton();
        invtry = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        reportsPanelOne = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        reportsPanelTwo = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        reportsPanelThree = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        mainPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        label.setText("Admin");
        welcomePanel.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 160, 60));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        welcomePanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 30));

        purchasing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/purchasing.png"))); // NOI18N
        purchasing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasingMouseExited(evt);
            }
        });
        welcomePanel.add(purchasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 170, 170));

        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/inventory.png"))); // NOI18N
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryMouseExited(evt);
            }
        });
        welcomePanel.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 330, 170, 170));

        miscellany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/miscellany.png"))); // NOI18N
        miscellany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miscellanyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miscellanyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miscellanyMouseExited(evt);
            }
        });
        welcomePanel.add(miscellany, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 330, 170, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/main.png"))); // NOI18N
        welcomePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(welcomePanel, "welcomePanel");

        purchasingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close1MouseExited(evt);
            }
        });
        purchasingPanel.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 28));

        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });
        purchasingPanel.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 90, 90));

        logOut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/logout.png"))); // NOI18N
        logOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOut1MouseExited(evt);
            }
        });
        purchasingPanel.add(logOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 30, 75, 89));

        prchOrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/prchord.png"))); // NOI18N
        prchOrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prchOrdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prchOrdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prchOrdMouseExited(evt);
            }
        });
        purchasingPanel.add(prchOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 105, 89));

        prchLst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/prchlst.png"))); // NOI18N
        prchLst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prchLstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prchLstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prchLstMouseExited(evt);
            }
        });
        purchasingPanel.add(prchLst, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 30, 105, 89));

        mainPurchasingPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPurchasingPanel.setLayout(new java.awt.CardLayout());

        purchasePanelOne.setBackground(new java.awt.Color(255, 255, 255));
        purchasePanelOne.setPreferredSize(new java.awt.Dimension(1024, 645));
        purchasePanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ss.png"))); // NOI18N
        selectSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectSupplierMouseExited(evt);
            }
        });
        purchasePanelOne.add(selectSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        receivedStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/rs.png"))); // NOI18N
        receivedStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivedStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receivedStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receivedStockMouseExited(evt);
            }
        });
        purchasePanelOne.add(receivedStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        returnsStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/rt.png"))); // NOI18N
        returnsStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnsStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnsStockMouseExited(evt);
            }
        });
        purchasePanelOne.add(returnsStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 6, 140, 30));

        supplierPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        supplierPanel.setLayout(new java.awt.CardLayout());

        supplierPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        supplierPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        supplierPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("View supplier Info");
        supplierPanelOne.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        supplierPanel.add(supplierPanelOne, "supplierPanelOne");

        supplierPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        supplierPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        supplierPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("stocks received");
        supplierPanelTwo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        supplierPanel.add(supplierPanelTwo, "supplierPanelTwo");

        supplierPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        supplierPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        supplierPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("returns stocks viewing");
        jLabel7.setToolTipText("");
        supplierPanelThree.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        supplierPanel.add(supplierPanelThree, "supplierPanelThree");

        purchasePanelOne.add(supplierPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 600));

        mainPurchasingPanel.add(purchasePanelOne, "purchasePanelOne");

        purchasePanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        purchasePanelTwo.setPreferredSize(new java.awt.Dimension(1024, 645));
        purchasePanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchasedOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/po.png"))); // NOI18N
        purchasedOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasedOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasedOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasedOrderMouseExited(evt);
            }
        });
        purchasePanelTwo.add(purchasedOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        unreceivedOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/uo.png"))); // NOI18N
        unreceivedOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unreceivedOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unreceivedOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unreceivedOrderMouseExited(evt);
            }
        });
        purchasePanelTwo.add(unreceivedOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        unpaidOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/upo.png"))); // NOI18N
        unpaidOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unpaidOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unpaidOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unpaidOrderMouseExited(evt);
            }
        });
        purchasePanelTwo.add(unpaidOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 5, 140, 30));

        purchaseListPanel.setBackground(new java.awt.Color(255, 255, 255));
        purchaseListPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        purchaseListPanel.setLayout(new java.awt.CardLayout());

        subPurchaseListPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        subPurchaseListPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subPurchaseListPanelOne.setPreferredSize(new java.awt.Dimension(0, 100));
        subPurchaseListPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Purchased Orders");
        subPurchaseListPanelOne.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        purchaseListPanel.add(subPurchaseListPanelOne, "subPurchaseListPanelOne");

        subPurchaseListPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        subPurchaseListPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subPurchaseListPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("unrcvd Orders");
        subPurchaseListPanelTwo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        purchaseListPanel.add(subPurchaseListPanelTwo, "subPurchaseListPanelTwo");

        subPurchaseListPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        subPurchaseListPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subPurchaseListPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Unpaid orders");
        subPurchaseListPanelThree.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        purchaseListPanel.add(subPurchaseListPanelThree, "subPurchaseListPanelThree");

        purchasePanelTwo.add(purchaseListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 600));

        mainPurchasingPanel.add(purchasePanelTwo, "purchasePanelTwo");

        purchasingPanel.add(mainPurchasingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 1024, 645));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/sub.png"))); // NOI18N
        purchasingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(purchasingPanel, "purchasingPanel");

        inventoryPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        inventoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close2MouseExited(evt);
            }
        });
        inventoryPanel.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 28));

        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
        });
        inventoryPanel.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 90, 90));

        logOut2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/logout.png"))); // NOI18N
        logOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOut2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOut2MouseExited(evt);
            }
        });
        inventoryPanel.add(logOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 30, 75, 89));

        stocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/stocks.png"))); // NOI18N
        stocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stocksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stocksMouseExited(evt);
            }
        });
        inventoryPanel.add(stocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 105, 89));

        products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/products.png"))); // NOI18N
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsMouseExited(evt);
            }
        });
        inventoryPanel.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 30, 105, 89));

        archery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/archery.png"))); // NOI18N
        archery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archeryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archeryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archeryMouseExited(evt);
            }
        });
        inventoryPanel.add(archery, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 30, 105, 89));

        mainInventoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainInventoryPanel.setLayout(new java.awt.CardLayout());

        inventoryPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        inventoryPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/cs.png"))); // NOI18N
        currentStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                currentStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                currentStockMouseExited(evt);
            }
        });
        inventoryPanelOne.add(currentStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        reOrderPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ros.png"))); // NOI18N
        reOrderPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reOrderPointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reOrderPointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reOrderPointMouseExited(evt);
            }
        });
        inventoryPanelOne.add(reOrderPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        adjustStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/as.png"))); // NOI18N
        adjustStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adjustStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adjustStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adjustStockMouseExited(evt);
            }
        });
        inventoryPanelOne.add(adjustStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 5, 140, 30));

        ledger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/l.png"))); // NOI18N
        ledger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ledgerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ledgerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ledgerMouseExited(evt);
            }
        });
        inventoryPanelOne.add(ledger, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, 140, 30));

        stocksPanel.setBackground(new java.awt.Color(255, 255, 255));
        stocksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stocksPanel.setLayout(new java.awt.CardLayout());

        stocksPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        stocksPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stocksPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Stocks Panel 1");
        stocksPanelOne.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        stocksPanel.add(stocksPanelOne, "stocksPanelOne");

        stocksPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        stocksPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stocksPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Stocks Panel 2");
        stocksPanelTwo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 63, -1, -1));

        stocksPanel.add(stocksPanelTwo, "stocksPanelTwo");

        stocksPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        stocksPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stocksPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Stocks Panel Three");
        stocksPanelThree.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        stocksPanel.add(stocksPanelThree, "stocksPanelThree");

        stocksPanelFour.setBackground(new java.awt.Color(255, 255, 255));
        stocksPanelFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stocksPanelFour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Stocks Panel 4");
        stocksPanelFour.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 118, -1, -1));

        stocksPanel.add(stocksPanelFour, "stocksPanelFour");

        inventoryPanelOne.add(stocksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 605));

        mainInventoryPanel.add(inventoryPanelOne, "inventoryPanelOne");

        inventoryPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        inventoryPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/np.png"))); // NOI18N
        newProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newProductMouseExited(evt);
            }
        });
        inventoryPanelTwo.add(newProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        productCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/pc.png"))); // NOI18N
        productCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productCategoryMouseExited(evt);
            }
        });
        inventoryPanelTwo.add(productCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        productList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/pl.png"))); // NOI18N
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productListMouseExited(evt);
            }
        });
        inventoryPanelTwo.add(productList, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 5, 140, 30));

        productsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productsPanel.setLayout(new java.awt.CardLayout());

        productsPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        productsPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productsPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("New Products");
        productsPanelOne.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        productsPanel.add(productsPanelOne, "productsPanelOne");

        productsPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        productsPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productsPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Product Category");
        productsPanelTwo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        productsPanel.add(productsPanelTwo, "productsPanelTwo");

        productsPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        productsPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productsPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Products List");
        productsPanelThree.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        productsPanel.add(productsPanelThree, "productsPanelThree");

        inventoryPanelTwo.add(productsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 645));

        mainInventoryPanel.add(inventoryPanelTwo, "inventoryPanelTwo");

        inventoryPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        inventoryPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Archery");
        inventoryPanelThree.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        mainInventoryPanel.add(inventoryPanelThree, "inventoryPanelThree");

        inventoryPanel.add(mainInventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 1024, 645));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/sub.png"))); // NOI18N
        inventoryPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(inventoryPanel, "inventoryPanel");

        miscellanyPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        miscellanyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close3MouseExited(evt);
            }
        });
        miscellanyPanel.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 28));

        back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back3MouseClicked(evt);
            }
        });
        miscellanyPanel.add(back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 90, 90));

        logOut3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/logout.png"))); // NOI18N
        logOut3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOut3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOut3MouseExited(evt);
            }
        });
        miscellanyPanel.add(logOut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 30, 75, 89));

        suppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/suppliers.png"))); // NOI18N
        suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliersMouseExited(evt);
            }
        });
        miscellanyPanel.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 105, 89));

        employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/employees.png"))); // NOI18N
        employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeesMouseExited(evt);
            }
        });
        miscellanyPanel.add(employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 30, 105, 89));

        orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/orders.png"))); // NOI18N
        orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersMouseExited(evt);
            }
        });
        miscellanyPanel.add(orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 30, 105, 89));

        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/reports.png"))); // NOI18N
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        miscellanyPanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 30, 105, 89));

        mainMiscellanyPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainMiscellanyPanel.setLayout(new java.awt.CardLayout());

        miscellanyPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        miscellanyPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ns.png"))); // NOI18N
        newSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newSupplierMouseExited(evt);
            }
        });
        miscellanyPanelOne.add(newSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        suppierList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/sl.png"))); // NOI18N
        suppierList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppierListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppierListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppierListMouseExited(evt);
            }
        });
        miscellanyPanelOne.add(suppierList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        suppliersPanel.setBackground(new java.awt.Color(255, 255, 255));
        suppliersPanel.setLayout(new java.awt.CardLayout());

        suppliersPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        suppliersPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        suppliersPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Supplier Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        suppliersPanelOne.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 580));

        add.setText("Add");
        suppliersPanelOne.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        save.setText("Save");
        suppliersPanelOne.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Supplier Name:");
        suppliersPanelOne.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        suppliersPanel.add(suppliersPanelOne, "suppliersPanelOne");

        suppliersPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        suppliersPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("Supplier List");

        javax.swing.GroupLayout suppliersPanelTwoLayout = new javax.swing.GroupLayout(suppliersPanelTwo);
        suppliersPanelTwo.setLayout(suppliersPanelTwoLayout);
        suppliersPanelTwoLayout.setHorizontalGroup(
            suppliersPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppliersPanelTwoLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel20)
                .addContainerGap(680, Short.MAX_VALUE))
        );
        suppliersPanelTwoLayout.setVerticalGroup(
            suppliersPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppliersPanelTwoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel20)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        suppliersPanel.add(suppliersPanelTwo, "suppliersPanelTwo");

        miscellanyPanelOne.add(suppliersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 605));

        mainMiscellanyPanel.add(miscellanyPanelOne, "miscellanyPanelOne");

        miscellanyPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        miscellanyPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ne.png"))); // NOI18N
        newEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newEmployeeMouseExited(evt);
            }
        });
        miscellanyPanelTwo.add(newEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        employeeList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/el.png"))); // NOI18N
        employeeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeListMouseExited(evt);
            }
        });
        miscellanyPanelTwo.add(employeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        employeesPanel.setBackground(new java.awt.Color(255, 255, 255));
        employeesPanel.setLayout(new java.awt.CardLayout());

        employeesPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        employeesPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("new Employee");

        javax.swing.GroupLayout employeesPanelOneLayout = new javax.swing.GroupLayout(employeesPanelOne);
        employeesPanelOne.setLayout(employeesPanelOneLayout);
        employeesPanelOneLayout.setHorizontalGroup(
            employeesPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelOneLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel21)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        employeesPanelOneLayout.setVerticalGroup(
            employeesPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelOneLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel21)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        employeesPanel.add(employeesPanelOne, "employeesPanelOne");

        employeesPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        employeesPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Employee List");

        javax.swing.GroupLayout employeesPanelTwoLayout = new javax.swing.GroupLayout(employeesPanelTwo);
        employeesPanelTwo.setLayout(employeesPanelTwoLayout);
        employeesPanelTwoLayout.setHorizontalGroup(
            employeesPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelTwoLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel22)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        employeesPanelTwoLayout.setVerticalGroup(
            employeesPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelTwoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel22)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        employeesPanel.add(employeesPanelTwo, "employeesPanelTwo");

        miscellanyPanelTwo.add(employeesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 645));

        mainMiscellanyPanel.add(miscellanyPanelTwo, "miscellanyPanelTwo");

        miscellanyPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        miscellanyPanelThree.setPreferredSize(new java.awt.Dimension(1024, 645));
        miscellanyPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Order Management");
        miscellanyPanelThree.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        mainMiscellanyPanel.add(miscellanyPanelThree, "miscellanyPanelThree");

        miscellanyPanelFour.setBackground(new java.awt.Color(255, 255, 255));
        miscellanyPanelFour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/s.png"))); // NOI18N
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesMouseExited(evt);
            }
        });
        miscellanyPanelFour.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 30));

        prchs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/p.png"))); // NOI18N
        prchs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prchsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prchsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prchsMouseExited(evt);
            }
        });
        miscellanyPanelFour.add(prchs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 140, 30));

        invtry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/i.png"))); // NOI18N
        invtry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invtryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invtryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invtryMouseExited(evt);
            }
        });
        miscellanyPanelFour.add(invtry, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 5, 140, 30));

        reportsPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportsPanel.setLayout(new java.awt.CardLayout());

        reportsPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        reportsPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportsPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Sales Report");
        reportsPanelOne.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        reportsPanel.add(reportsPanelOne, "reportsPanelOne");

        reportsPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        reportsPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportsPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Purchasing Reports");
        reportsPanelTwo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        reportsPanel.add(reportsPanelTwo, "reportsPanelTwo");

        reportsPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        reportsPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportsPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("Inventory Report");
        reportsPanelThree.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        reportsPanel.add(reportsPanelThree, "reportsPanelThree");

        miscellanyPanelFour.add(reportsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1024, 605));

        mainMiscellanyPanel.add(miscellanyPanelFour, "miscellanyPanelFour");

        miscellanyPanel.add(mainMiscellanyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 1024, 645));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/sub.png"))); // NOI18N
        miscellanyPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(miscellanyPanel, "miscellanyPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close.setIcon(ico);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void purchasingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/purchasinghvr.png"));
        purchasing.setIcon(ico);
    }//GEN-LAST:event_purchasingMouseEntered

    private void purchasingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/purchasing.png"));
        purchasing.setIcon(ico);
    }//GEN-LAST:event_purchasingMouseExited

    private void purchasingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "purchasingPanel");
    }//GEN-LAST:event_purchasingMouseClicked

    private void inventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/inventoryhvr.png"));
        inventory.setIcon(ico);
    }//GEN-LAST:event_inventoryMouseEntered

    private void inventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/inventory.png"));
        inventory.setIcon(ico);
    }//GEN-LAST:event_inventoryMouseExited

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "inventoryPanel");
    }//GEN-LAST:event_inventoryMouseClicked

    private void miscellanyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miscellanyMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/miscellanyhvr.png"));
        miscellany.setIcon(ico);
    }//GEN-LAST:event_miscellanyMouseEntered

    private void miscellanyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miscellanyMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/miscellany.png"));
        miscellany.setIcon(ico);
    }//GEN-LAST:event_miscellanyMouseExited

    private void miscellanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miscellanyMouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "miscellanyPanel");
    }//GEN-LAST:event_miscellanyMouseClicked

    private void close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close1.setIcon(ico);
    }//GEN-LAST:event_close1MouseEntered

    private void close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close1.setIcon(null);
    }//GEN-LAST:event_close1MouseExited

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "welcomePanel");
    }//GEN-LAST:event_back1MouseClicked

    private void logOut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut1MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOuthvr.png"));
       logOut1.setIcon(ico);
    }//GEN-LAST:event_logOut1MouseEntered

    private void logOut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut1MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOut.png"));
       logOut1.setIcon(ico);
    }//GEN-LAST:event_logOut1MouseExited

    private void logOut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logOut1MouseClicked

    private void prchOrdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchOrdMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/prchordhvr.png"));
       prchOrd.setIcon(ico);
    }//GEN-LAST:event_prchOrdMouseEntered

    private void prchOrdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchOrdMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/prchord.png"));
       prchOrd.setIcon(ico);
    }//GEN-LAST:event_prchOrdMouseExited

    private void prchOrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchOrdMouseClicked
        CardLayout admin = (CardLayout) mainPurchasingPanel.getLayout();
        admin.show(mainPurchasingPanel, "purchasePanelOne");
    }//GEN-LAST:event_prchOrdMouseClicked

    private void prchLstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchLstMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/prchlsthvr.png"));
       prchLst.setIcon(ico);
    }//GEN-LAST:event_prchLstMouseEntered

    private void prchLstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchLstMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/prchlst.png"));
       prchLst.setIcon(ico);
    }//GEN-LAST:event_prchLstMouseExited

    private void prchLstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchLstMouseClicked
        CardLayout admin = (CardLayout) mainPurchasingPanel.getLayout();
        admin.show(mainPurchasingPanel, "purchasePanelTwo");
    }//GEN-LAST:event_prchLstMouseClicked

    private void selectSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSupplierMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/sshvr.png"));
       selectSupplier.setIcon(ico);
    }//GEN-LAST:event_selectSupplierMouseEntered

    private void selectSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSupplierMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ss.png"));
       selectSupplier.setIcon(ico);
    }//GEN-LAST:event_selectSupplierMouseExited

    private void selectSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSupplierMouseClicked
        CardLayout admin = (CardLayout) supplierPanel.getLayout();
        admin.show(supplierPanel, "supplierPanelOne");
    }//GEN-LAST:event_selectSupplierMouseClicked

    private void receivedStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivedStockMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/rshvr.png"));
       receivedStock.setIcon(ico);
    }//GEN-LAST:event_receivedStockMouseEntered

    private void receivedStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivedStockMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/rs.png"));
       receivedStock.setIcon(ico);
    }//GEN-LAST:event_receivedStockMouseExited

    private void receivedStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivedStockMouseClicked
        CardLayout admin = (CardLayout) supplierPanel.getLayout();
        admin.show(supplierPanel, "supplierPanelTwo");
    }//GEN-LAST:event_receivedStockMouseClicked

    private void returnsStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsStockMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/rthvr.png"));
       returnsStock.setIcon(ico);
    }//GEN-LAST:event_returnsStockMouseEntered

    private void returnsStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsStockMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/rt.png"));
       returnsStock.setIcon(ico);
    }//GEN-LAST:event_returnsStockMouseExited

    private void returnsStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsStockMouseClicked
       CardLayout admin = (CardLayout) supplierPanel.getLayout();
       admin.show(supplierPanel, "supplierPanelThree");
    }//GEN-LAST:event_returnsStockMouseClicked

    private void purchasedOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedOrderMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/pohvr.png"));
       purchasedOrder.setIcon(ico);
    }//GEN-LAST:event_purchasedOrderMouseEntered

    private void purchasedOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedOrderMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/po.png"));
       purchasedOrder.setIcon(ico);
    }//GEN-LAST:event_purchasedOrderMouseExited

    private void purchasedOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedOrderMouseClicked
       CardLayout admin = (CardLayout) purchaseListPanel.getLayout();
       admin.show(purchaseListPanel, "subPurchaseListPanelOne");
    }//GEN-LAST:event_purchasedOrderMouseClicked

    private void unreceivedOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unreceivedOrderMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/uohvr.png"));
       unreceivedOrder.setIcon(ico);
    }//GEN-LAST:event_unreceivedOrderMouseEntered

    private void unreceivedOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unreceivedOrderMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/uo.png"));
        unreceivedOrder.setIcon(ico);
    }//GEN-LAST:event_unreceivedOrderMouseExited

    private void unreceivedOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unreceivedOrderMouseClicked
       CardLayout admin = (CardLayout) purchaseListPanel.getLayout();
       admin.show(purchaseListPanel, "subPurchaseListPanelTwo");
    }//GEN-LAST:event_unreceivedOrderMouseClicked

    private void unpaidOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unpaidOrderMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/upohvr.png"));
       unpaidOrder.setIcon(ico);
    }//GEN-LAST:event_unpaidOrderMouseEntered

    private void unpaidOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unpaidOrderMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/upo.png"));
       unpaidOrder.setIcon(ico);
    }//GEN-LAST:event_unpaidOrderMouseExited

    private void unpaidOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unpaidOrderMouseClicked
       CardLayout admin = (CardLayout) purchaseListPanel.getLayout();
       admin.show(purchaseListPanel, "subPurchaseListPanelThree");
    }//GEN-LAST:event_unpaidOrderMouseClicked

    private void close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close2.setIcon(ico);
    }//GEN-LAST:event_close2MouseEntered

    private void close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close2.setIcon(null);
    }//GEN-LAST:event_close2MouseExited

    private void close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close2MouseClicked

    private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "welcomePanel");
    }//GEN-LAST:event_back2MouseClicked

    private void logOut2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut2MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOuthvr.png"));
       logOut2.setIcon(ico);
    }//GEN-LAST:event_logOut2MouseEntered

    private void logOut2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut2MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOut.png"));
       logOut2.setIcon(ico);
    }//GEN-LAST:event_logOut2MouseExited

    private void logOut2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logOut2MouseClicked

    private void stocksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocksMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/stockshvr.png"));
       stocks.setIcon(ico);
    }//GEN-LAST:event_stocksMouseEntered

    private void stocksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocksMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/stocks.png"));
       stocks.setIcon(ico);
    }//GEN-LAST:event_stocksMouseExited

    private void stocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocksMouseClicked
       CardLayout admin = (CardLayout) mainInventoryPanel.getLayout();
       admin.show(mainInventoryPanel, "inventoryPanelOne");
    }//GEN-LAST:event_stocksMouseClicked

    private void productsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/productshvr.png"));
       products.setIcon(ico);
    }//GEN-LAST:event_productsMouseEntered

    private void productsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/products.png"));
       products.setIcon(ico);
    }//GEN-LAST:event_productsMouseExited

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked
       CardLayout admin = (CardLayout) mainInventoryPanel.getLayout();
       admin.show(mainInventoryPanel, "inventoryPanelTwo");
    }//GEN-LAST:event_productsMouseClicked

    private void archeryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/archeryhvr.png"));
       archery.setIcon(ico);
    }//GEN-LAST:event_archeryMouseEntered

    private void archeryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/archery.png"));
       archery.setIcon(ico);
    }//GEN-LAST:event_archeryMouseExited

    private void archeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseClicked
       CardLayout admin = (CardLayout) mainInventoryPanel.getLayout();
       admin.show(mainInventoryPanel, "inventoryPanelThree");
    }//GEN-LAST:event_archeryMouseClicked

    private void currentStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentStockMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/cshvr.png"));
       currentStock.setIcon(ico);
    }//GEN-LAST:event_currentStockMouseEntered

    private void currentStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentStockMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/cs.png"));
       currentStock.setIcon(ico);
    }//GEN-LAST:event_currentStockMouseExited

    private void currentStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentStockMouseClicked
       CardLayout admin = (CardLayout) stocksPanel.getLayout();
       admin.show(stocksPanel, "stocksPanelOne");
    }//GEN-LAST:event_currentStockMouseClicked

    private void reOrderPointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reOrderPointMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/roshvr.png"));
       reOrderPoint.setIcon(ico);
    }//GEN-LAST:event_reOrderPointMouseEntered

    private void reOrderPointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reOrderPointMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ros.png"));
       reOrderPoint.setIcon(ico);
    }//GEN-LAST:event_reOrderPointMouseExited

    private void reOrderPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reOrderPointMouseClicked
       CardLayout admin = (CardLayout) stocksPanel.getLayout();
       admin.show(stocksPanel, "stocksPanelTwo");
    }//GEN-LAST:event_reOrderPointMouseClicked

    private void adjustStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adjustStockMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ashvr.png"));
       adjustStock.setIcon(ico);
    }//GEN-LAST:event_adjustStockMouseEntered

    private void adjustStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adjustStockMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/as.png"));
       adjustStock.setIcon(ico);
    }//GEN-LAST:event_adjustStockMouseExited

    private void adjustStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adjustStockMouseClicked
       CardLayout admin = (CardLayout) stocksPanel.getLayout();
       admin.show(stocksPanel, "stocksPanelThree");
    }//GEN-LAST:event_adjustStockMouseClicked

    private void ledgerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ledgerMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/lhvr.png"));
       ledger.setIcon(ico);
    }//GEN-LAST:event_ledgerMouseEntered

    private void ledgerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ledgerMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/l.png"));
       ledger.setIcon(ico);
    }//GEN-LAST:event_ledgerMouseExited

    private void ledgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ledgerMouseClicked
       CardLayout admin = (CardLayout) stocksPanel.getLayout();
       admin.show(stocksPanel, "stocksPanelFour");
    }//GEN-LAST:event_ledgerMouseClicked

    private void newProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProductMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/nphvr.png"));
       newProduct.setIcon(ico);
    }//GEN-LAST:event_newProductMouseEntered

    private void newProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProductMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/np.png"));
       newProduct.setIcon(ico);
    }//GEN-LAST:event_newProductMouseExited

    private void newProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProductMouseClicked
       CardLayout admin = (CardLayout) productsPanel.getLayout();
       admin.show(productsPanel, "productsPanelOne");
    }//GEN-LAST:event_newProductMouseClicked

    private void productCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCategoryMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/pchvr.png"));
       productCategory.setIcon(ico);
    }//GEN-LAST:event_productCategoryMouseEntered

    private void productCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCategoryMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/pc.png"));
       productCategory.setIcon(ico);
    }//GEN-LAST:event_productCategoryMouseExited

    private void productCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCategoryMouseClicked
       CardLayout admin = (CardLayout) productsPanel.getLayout();
       admin.show(productsPanel, "productsPanelTwo");
    }//GEN-LAST:event_productCategoryMouseClicked

    private void productListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/plhvr.png"));
       productList.setIcon(ico);
    }//GEN-LAST:event_productListMouseEntered

    private void productListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/pl.png"));
       productList.setIcon(ico);
    }//GEN-LAST:event_productListMouseExited

    private void productListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseClicked
       CardLayout admin = (CardLayout) productsPanel.getLayout();
       admin.show(productsPanel, "productsPanelThree");
    }//GEN-LAST:event_productListMouseClicked

    private void close3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close3.setIcon(ico);
    }//GEN-LAST:event_close3MouseEntered

    private void close3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
       close3.setIcon(null);
    }//GEN-LAST:event_close3MouseExited

    private void close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseClicked
       System.exit(0);
    }//GEN-LAST:event_close3MouseClicked

    private void back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back3MouseClicked
        CardLayout admin = (CardLayout) mainPanel.getLayout();
        admin.show(mainPanel, "welcomePanel");
    }//GEN-LAST:event_back3MouseClicked

    private void suppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/suppliershvr.png"));
       suppliers.setIcon(ico);
    }//GEN-LAST:event_suppliersMouseEntered

    private void suppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/suppliers.png"));
       suppliers.setIcon(ico);
    }//GEN-LAST:event_suppliersMouseExited

    private void suppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseClicked
        CardLayout admin = (CardLayout) mainMiscellanyPanel.getLayout();
        admin.show(mainMiscellanyPanel, "miscellanyPanelOne");
    }//GEN-LAST:event_suppliersMouseClicked

    private void employeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/employeeshvr.png"));
       employees.setIcon(ico);
    }//GEN-LAST:event_employeesMouseEntered

    private void employeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/employees.png"));
       employees.setIcon(ico);
    }//GEN-LAST:event_employeesMouseExited

    private void employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseClicked
        CardLayout admin = (CardLayout) mainMiscellanyPanel.getLayout();
        admin.show(mainMiscellanyPanel, "miscellanyPanelTwo");
    }//GEN-LAST:event_employeesMouseClicked

    private void ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ordershvr.png"));
       orders.setIcon(ico);
    }//GEN-LAST:event_ordersMouseEntered

    private void ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/orders.png"));
       orders.setIcon(ico);
    }//GEN-LAST:event_ordersMouseExited

    private void ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseClicked
        CardLayout admin = (CardLayout) mainMiscellanyPanel.getLayout();
        admin.show(mainMiscellanyPanel, "miscellanyPanelThree");
    }//GEN-LAST:event_ordersMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/reportshvr.png"));
       reports.setIcon(ico);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/reports.png"));
       reports.setIcon(ico);
    }//GEN-LAST:event_reportsMouseExited

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        CardLayout admin = (CardLayout) mainMiscellanyPanel.getLayout();
        admin.show(mainMiscellanyPanel, "miscellanyPanelFour");
    }//GEN-LAST:event_reportsMouseClicked

    private void logOut3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut3MouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOuthvr.png"));
       logOut3.setIcon(ico);
    }//GEN-LAST:event_logOut3MouseEntered

    private void logOut3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut3MouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logOut.png"));
       logOut3.setIcon(ico);
    }//GEN-LAST:event_logOut3MouseExited

    private void logOut3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logOut3MouseClicked

    private void newSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupplierMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/nshvr.png"));
       newSupplier.setIcon(ico);
    }//GEN-LAST:event_newSupplierMouseEntered

    private void newSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupplierMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ns.png"));
       newSupplier.setIcon(ico);
    }//GEN-LAST:event_newSupplierMouseExited

    private void newSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupplierMouseClicked
        CardLayout admin = (CardLayout) suppliersPanel.getLayout();
        admin.show(suppliersPanel, "suppliersPanelOne");
    }//GEN-LAST:event_newSupplierMouseClicked

    private void suppierListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppierListMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/slhvr.png"));
       suppierList.setIcon(ico);
    }//GEN-LAST:event_suppierListMouseEntered

    private void suppierListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppierListMouseExited
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/sl.png"));
       suppierList.setIcon(ico);
    }//GEN-LAST:event_suppierListMouseExited

    private void suppierListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppierListMouseClicked
        CardLayout admin = (CardLayout) suppliersPanel.getLayout();
        admin.show(suppliersPanel, "suppliersPanelTwo");
    }//GEN-LAST:event_suppierListMouseClicked

    private void newEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmployeeMouseEntered
       ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/nehvr.png"));
       newEmployee.setIcon(ico);
    }//GEN-LAST:event_newEmployeeMouseEntered

    private void newEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmployeeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ne.png"));
        newEmployee.setIcon(ico);
    }//GEN-LAST:event_newEmployeeMouseExited

    private void newEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmployeeMouseClicked
        CardLayout admin = (CardLayout) employeesPanel.getLayout();
        admin.show(employeesPanel, "employeesPanelOne");
    }//GEN-LAST:event_newEmployeeMouseClicked

    private void employeeListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeListMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/elhvr.png"));
        employeeList.setIcon(ico);
    }//GEN-LAST:event_employeeListMouseEntered

    private void employeeListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeListMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/el.png"));
        employeeList.setIcon(ico);
    }//GEN-LAST:event_employeeListMouseExited

    private void employeeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeListMouseClicked
        CardLayout admin = (CardLayout) employeesPanel.getLayout();
        admin.show(employeesPanel, "employeesPanelTwo");
    }//GEN-LAST:event_employeeListMouseClicked

    private void salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/shvr.png"));
        sales.setIcon(ico);
    }//GEN-LAST:event_salesMouseEntered

    private void salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/s.png"));
        sales.setIcon(ico);
    }//GEN-LAST:event_salesMouseExited

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        CardLayout admin = (CardLayout) reportsPanel.getLayout();
        admin.show(reportsPanel, "reportsPanelOne");
    }//GEN-LAST:event_salesMouseClicked

    private void prchsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchsMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/phvr.png"));
        prchs.setIcon(ico);
    }//GEN-LAST:event_prchsMouseEntered

    private void prchsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchsMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/p.png"));
        prchs.setIcon(ico);
    }//GEN-LAST:event_prchsMouseExited

    private void prchsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prchsMouseClicked
        CardLayout admin = (CardLayout) reportsPanel.getLayout();
        admin.show(reportsPanel, "reportsPanelTwo");
    }//GEN-LAST:event_prchsMouseClicked

    private void invtryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invtryMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ihvr.png"));
        invtry.setIcon(ico);
    }//GEN-LAST:event_invtryMouseEntered

    private void invtryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invtryMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/i.png"));
        invtry.setIcon(ico);
    }//GEN-LAST:event_invtryMouseExited

    private void invtryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invtryMouseClicked
        CardLayout admin = (CardLayout) reportsPanel.getLayout();
        admin.show(reportsPanel, "reportsPanelThree");
    }//GEN-LAST:event_invtryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton adjustStock;
    private javax.swing.JButton archery;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel back3;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JLabel close3;
    private javax.swing.JButton currentStock;
    private javax.swing.JButton employeeList;
    private javax.swing.JButton employees;
    private javax.swing.JPanel employeesPanel;
    private javax.swing.JPanel employeesPanelOne;
    private javax.swing.JPanel employeesPanelTwo;
    private javax.swing.JButton inventory;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JPanel inventoryPanelOne;
    private javax.swing.JPanel inventoryPanelThree;
    private javax.swing.JPanel inventoryPanelTwo;
    private javax.swing.JButton invtry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    private javax.swing.JButton ledger;
    private javax.swing.JButton logOut1;
    private javax.swing.JButton logOut2;
    private javax.swing.JButton logOut3;
    private javax.swing.JPanel mainInventoryPanel;
    private javax.swing.JPanel mainMiscellanyPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPurchasingPanel;
    private javax.swing.JButton miscellany;
    private javax.swing.JPanel miscellanyPanel;
    private javax.swing.JPanel miscellanyPanelFour;
    private javax.swing.JPanel miscellanyPanelOne;
    private javax.swing.JPanel miscellanyPanelThree;
    private javax.swing.JPanel miscellanyPanelTwo;
    private javax.swing.JButton newEmployee;
    private javax.swing.JButton newProduct;
    private javax.swing.JButton newSupplier;
    private javax.swing.JButton orders;
    private javax.swing.JButton prchLst;
    private javax.swing.JButton prchOrd;
    private javax.swing.JButton prchs;
    private javax.swing.JButton productCategory;
    private javax.swing.JButton productList;
    private javax.swing.JButton products;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JPanel productsPanelOne;
    private javax.swing.JPanel productsPanelThree;
    private javax.swing.JPanel productsPanelTwo;
    private javax.swing.JPanel purchaseListPanel;
    private javax.swing.JPanel purchasePanelOne;
    private javax.swing.JPanel purchasePanelTwo;
    private javax.swing.JButton purchasedOrder;
    private javax.swing.JButton purchasing;
    private javax.swing.JPanel purchasingPanel;
    private javax.swing.JButton reOrderPoint;
    private javax.swing.JButton receivedStock;
    private javax.swing.JButton reports;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JPanel reportsPanelOne;
    private javax.swing.JPanel reportsPanelThree;
    private javax.swing.JPanel reportsPanelTwo;
    private javax.swing.JButton returnsStock;
    private javax.swing.JButton sales;
    private javax.swing.JButton save;
    private javax.swing.JButton selectSupplier;
    private javax.swing.JButton stocks;
    private javax.swing.JPanel stocksPanel;
    private javax.swing.JPanel stocksPanelFour;
    private javax.swing.JPanel stocksPanelOne;
    private javax.swing.JPanel stocksPanelThree;
    private javax.swing.JPanel stocksPanelTwo;
    private javax.swing.JPanel subPurchaseListPanelOne;
    private javax.swing.JPanel subPurchaseListPanelThree;
    private javax.swing.JPanel subPurchaseListPanelTwo;
    private javax.swing.JButton suppierList;
    private javax.swing.JPanel supplierPanel;
    private javax.swing.JPanel supplierPanelOne;
    private javax.swing.JPanel supplierPanelThree;
    private javax.swing.JPanel supplierPanelTwo;
    private javax.swing.JButton suppliers;
    private javax.swing.JPanel suppliersPanel;
    private javax.swing.JPanel suppliersPanelOne;
    private javax.swing.JPanel suppliersPanelTwo;
    private javax.swing.JButton unpaidOrder;
    private javax.swing.JButton unreceivedOrder;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
